### ISSUE TITLE
npm test fails

### ISSUE THREAD

**Issue by peterennis** [Saqib92/ionic-4-Sidemenu-with-Tabs#1]
![Capture239](https://user-images.githubusercontent.com/140737/60939120-6af36280-a28b-11e9-82dd-93711752e540.png)

**Comment by Saqib92** [comment]
if you have fixed it. please close this issue.

**Comment by peterennis** [comment]
@Saqib92 
This is not fixed.
The PR https://github.com/Saqib92/ionic-4-Sidemenu-with-Tabs/pull/3
will close https://github.com/Saqib92/ionic-4-Sidemenu-with-Tabs/issues/2
Please verify then merge.

You should look into fixing the tests. I do not have time now.
